openapi: 3.1.0
info:
  version: 1.0.0
  title: TV Library Backend
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |-
    This is a documentation for TV Library Server based on the OpenAPI 3.0 specification. 
    Some useful links:
    - [TV Library Backend repository](https://github.com/DmytriiTsybuliak/movies-library-backend)
    - [The source API definition for the TV Library Backend](https://github.com/DmytriiTsybuliak/movies-library-backend/blob/main/src/docs/openapi.yaml)
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: Favorite
    description: List of saved movies and TV shows for users.
  - name: Auth
    description: Operations about user.
servers:
  - url: https://movies-library-backend-s1fd.onrender.com
paths:
  /auth/register:
    $ref: './swagger/path/auth/register.yaml'
  /auth/login:
    $ref: './swagger/path/auth/login.yaml'
  /auth/logout:
    $ref: './swagger/path/auth/logout.yaml'
  /auth/refresh:
    $ref: './swagger/path/auth/refresh.yaml'
  /auth/request-reset-email:
    $ref: './swagger/path/auth/request-reset-email.yaml'
  /auth/reset-password:
    $ref: './swagger/path/auth/reset-password.yaml'
  /auth/get-oauth-url:
    $ref: './swagger/path/auth/get-oauth-url.yaml'
  /auth/confirm-google-auth:
    $ref: './swagger/path/auth/confirm-google-auth.yaml'
  /favorite:
    $ref: './swagger/path/favorite/favorite.yaml'
  /favorite/{favoriteID}:
    $ref: './swagger/path/favorite/delete.yaml'
  /user/me:
    $ref: './swagger/path/user/get.yaml'
  /user/update:
    $ref: './swagger/path/user/patch.yaml'
  /user/delete:
    $ref: './swagger/path/user/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId
